services:
  frontend:
    build: ./apps/frontend
    ports:
      - "3000:3000"
    environment:
      FC_PROXY_TARGET: http://file-converter:8080

  file-converter:
    build:
      context: ./apps/file-converter
      target: dev
    ports:
      - "8080:8080"
      - "2345:2345"